apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar-web
  template:
    metadata:
      labels:
        app: hotstar-web
    spec:
      containers:
        - name: hotstar-cont
          image: sriramyaganni/hotstar-webapp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-loadbalancer
spec:
  selector:
    app: hotstar-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-clusterip
spec:
  selector:
    app: hotstar-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

